import { prisma } from '@/server.js'

const seed = async () => {
  await prisma.auth.createMany({
    data: [
      {
        id: 0,
        uuid: '6babc75d-30ea-4d49-8b7d-3fffb2ddbcec',
        type: 'Administrador',
        admin: true,
        project: true,
        personal: true,
        financial: true,
      },
      {
        id: 1,
        uuid: 'a42d15c4-6721-4b15-84de-b5fa8ab86bac',
        type: 'Sócio',
        admin: true,
        project: true,
        personal: false,
        financial: true,
      },
      {
        id: 2,
        uuid: '011ea0b9-786c-4833-b8a9-f060b604f242',
        type: 'Consultor',
        admin: false,
        project: true,
        personal: false,
        financial: true,
      },
      {
        id: 3,
        uuid: '60e3d518-e670-4781-9762-63cc0c2888b6',
        type: 'RH',
        admin: false,
        project: false,
        personal: true,
        financial: true,
      },
      {
        id: 4,
        uuid: '462ac957-2f54-4222-af77-55742fd31d44',
        type: 'Financeiro',
        admin: false,
        project: false,
        personal: false,
        financial: true,
      },
      {
        id: 5,
        uuid: 'f8eb44b1-cb47-4c47-a518-aa0d081c856f',
        type: 'Estagiário',
        admin: false,
        project: false,
        personal: false,
        financial: false,
      },
    ],
    skipDuplicates: true,
  })
  await prisma.status.createMany({
    data: [
      {
        id: 1,
        name: 'Planejamento',
        description: 'Está em fase de definição e planejamento',
        priority: 5,
      },
      {
        id: 2,
        name: 'Negociação',
        description: 'Está em fase orçamento e negociação',
        priority: 6,
      },
      {
        id: 3,
        name: 'Aguardando Aprovação',
        description: 'O projeto aguarda aprovação antes de iniciar',
        priority: 7,
      },
      {
        id: 4,
        name: 'Não Iniciado',
        description: 'O projeto foi aprovado, mas ainda não começou',
        priority: 4,
      },
      {
        id: 5,
        name: 'Em Andamento',
        description: 'O projeto está em execução',
        priority: 3,
      },
      {
        id: 6,
        name: 'Suspenso',
        description: 'O projeto foi temporariamente interrompido',
        priority: 1,
      },
      {
        id: 7,
        name: 'Atrasado',
        description: 'O projeto está em execução, mas atrasado em relação ao cronograma',
        priority: 2,
      },
      {
        id: 8,
        name: 'Aguardando Recursos',
        description: 'O projeto não pode continuar ou começar porque está aguardando recursos',
        priority: 3,
      },
      {
        id: 9,
        name: 'Concluído',
        description: 'O projeto foi concluído com sucesso',
        priority: 9,
      },
      {
        id: 10,
        name: 'Cancelado',
        description: 'O projeto foi encerrado antes de ser concluído',
        priority: 10,
      },
      {
        id: 11,
        name: 'Encerrado',
        description: 'O projeto foi oficialmente fechado',
        priority: 8,
      },
    ],
    skipDuplicates: true,
  })
  await prisma.user.createMany({
    data: [
      {
        id: 0,
        cpf: '000.000.000-00',
        photo: undefined,
        name: 'Administrador',
        username: 'Admin',
        email: 'admin@profitly.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        phone: undefined,
        active: true,
        hourlyRate: undefined,
        authUuid: '6babc75d-30ea-4d49-8b7d-3fffb2ddbcec',
      },
      {
        id: 1,
        cpf: '123.456.789-10',
        name: 'John Doe',
        username: 'johndoe',
        email: 'john@example.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        phone: '(99) 9 9999-9999',
        active: true,
        hourlyRate: 500,
        authUuid: 'a42d15c4-6721-4b15-84de-b5fa8ab86bac',
      },
      {
        id: 2,
        cpf: '987.654.321-00',
        name: 'Alice Brown',
        username: 'alicebrown',
        email: 'alice@example.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        phone: '(00) 0 0000-0000',
        active: true,
        hourlyRate: 300,
        authUuid: '011ea0b9-786c-4833-b8a9-f060b604f242',
      },
      {
        id: 3,
        cpf: '456.789.123-99',
        name: 'Diana Blue',
        username: 'dianablue',
        email: 'diana@example.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        active: true,
        authUuid: '60e3d518-e670-4781-9762-63cc0c2888b6',
      },
      {
        id: 4,
        cpf: '321.654.987-88',
        name: 'Charlie Green',
        username: 'charliegreen',
        email: 'charlie@example.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        phone: '(88) 8 8888-8888',
        active: true,
        authUuid: '462ac957-2f54-4222-af77-55742fd31d44',
      },
      {
        id: 5,
        cpf: '654.321.987-77',
        name: 'Jane Smith',
        username: 'janesmith',
        email: 'jane@example.com',
        password: '$2b$10$/EHRDH.8WNn04Cul7EVBGuQsGDG/GQBTRrwU6F4ln.0tsWS/PAhGy',
        active: true,
        authUuid: 'f8eb44b1-cb47-4c47-a518-aa0d081c856f',
      },
    ],
    skipDuplicates: true,
  })
  await prisma.client.createMany({
    data: [
      {
        id: 1,
        type: 'Enterprise',
        cnpj: '14.725.836/0001-01',
        name: 'Alpha Inc',
        fantasy: 'Alpha',
        email: 'contact@alpha.com',
        phone: '(99) 9 9999-9999',
        active: true,
      },
      {
        id: 2,
        type: 'Enterprise',
        cnpj: '78.912.345/0001-02',
        name: 'Delta Ltd',
        fantasy: 'Delta',
        email: 'contact@delta.com',
        phone: '(00) 0 0000-0000',
        active: true,
      },
      {
        id: 3,
        type: 'Enterprise',
        cnpj: '36.985.214/0002-02',
        name: 'Epsilon LLC',
        fantasy: 'Epsilon',
        email: 'contact@epsilon.com',
        phone: null,
        active: true,
      },
      {
        id: 4,
        type: 'Enterprise',
        cnpj: '75.315.948/0001-03',
        name: 'Gamma Co',
        fantasy: 'Gamma',
        email: 'contact@gamma.com',
        phone: '(88) 8 8888-8888',
        active: false,
      },
      {
        id: 5,
        type: 'Enterprise',
        cnpj: '95.135.762/0002-02',
        name: 'Lambda SA',
        fantasy: 'Lambda',
        email: 'contact@lambda.com',
        phone: null,
        active: true,
      },
      {
        id: 6,
        type: 'Person',
        cpf: '123.456.789-00',
        name: 'Teta',
        email: 'contact@teta.com',
        phone: '(99) 9 9999-9999',
        active: true,
      },
      {
        id: 7,
        type: 'Person',
        cpf: '987.654.321-99',
        name: 'Ômega',
        email: 'contact@omega.com',
        phone: '(00) 0 0000-0000',
        active: false,
      },
      {
        id: 8,
        type: 'Person',
        cpf: '000.000.000-99',
        name: 'Sigma',
        email: 'contact@sigma.com',
        phone: null,
        active: true,
      },
    ],
    skipDuplicates: true,
  })
  await prisma.supplier.createMany({
    data: [
      {
        id: 1,
        type: 'Enterprise',
        cnpj: '14.725.836/0001-01',
        name: 'Alpha Inc',
        fantasy: 'Alpha',
        email: 'contact@alpha.com',
        phone: '(99) 9 9999-9999',
        active: true,
        address: '456 Oak Avenue, Toronto, ON, M4B 1B4, Canada',
      },
      {
        id: 2,
        type: 'Enterprise',
        cnpj: '78.912.345/0001-02',
        name: 'Delta Ltd',
        fantasy: 'Delta',
        email: 'contact@delta.com',
        phone: '(00) 0 0000-0000',
        active: true,
        address: '123 Elm Street, Springfield, IL, 62704, USA',
      },
      {
        id: 3,
        type: 'Enterprise',
        cnpj: '36.985.214/0002-02',
        name: 'Epsilon LLC',
        fantasy: 'Epsilon',
        email: 'contact@epsilon.com',
        phone: null,
        active: true,
        address: null,
      },
      {
        id: 4,
        type: 'Enterprise',
        cnpj: '75.315.948/0001-03',
        name: 'Gamma Co',
        fantasy: 'Gamma',
        email: 'contact@gamma.com',
        phone: '(88) 8 8888-8888',
        active: false,
        address: '789 Pine Lane, Sydney, NSW, 2000, Australia',
      },
      {
        id: 5,
        type: 'Enterprise',
        cnpj: '95.135.762/0002-02',
        name: 'Lambda SA',
        fantasy: 'Lambda',
        email: 'contact@lambda.com',
        phone: null,
        active: true,
        address: '404 Walnut Way, Berlin, 10115, Germany',
      },
      {
        id: 6,
        type: 'Person',
        cpf: '123.456.789-00',
        name: 'Teta',
        email: 'contact@teta.com',
        phone: '(99) 9 9999-9999',
        active: true,
        address: null,
      },
      {
        id: 7,
        type: 'Person',
        cpf: '987.654.321-99',
        name: 'Ômega',
        email: 'contact@omega.com',
        phone: '(00) 0 0000-0000',
        active: false,
        address: '101 Maple Road, London, SW1A 1AA, UK',
      },
      {
        id: 8,
        type: 'Person',
        cpf: '000.000.000-99',
        name: 'Sigma',
        email: 'contact@sigma.com',
        phone: null,
        active: true,
        address: '303 Cedar Boulevard, Tokyo, 100-0001, Japan',
      },
    ],
    skipDuplicates: true,
  })
}

seed().then(() => {
  console.log('Database seeded!')
  prisma.$disconnect()
})
